config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [ :index, :show, :new, :create, :edit, :update, :destroy]
  resources :companies, only: [ :index, :show, :new, :create, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
     has_many :involved_company, dependent: :delete_all
     has_many :games, through: :involved_company
     has_many :reviews, as: :reviewable

     validates :name, :country, presence: true
     validates :name, uniqueness: true
end

app/models/game.rb
class Game < ApplicationRecord
     has_many :involved_company, dependent: :delete_all
     has_many :companies, through: :involved_company
     has_and_belongs_to_many :platforms
     has_and_belongs_to_many :genres
     has_many :expansions, class_name: 'Game', foreign_key: 'parent_id'
     belongs_to :parent, class_name: 'Game', optional: true
     has_many :reviews, as: :reviewable
     enum category: { main_game: 0, expansion:1}

     validates :name, presence: true, uniqueness: true
     validates :category, presence: true
     validates :rating, inclusion: {in: 0..100}, allow_nil: true
     validates :parent_id, presence: true, if: :parent_id_custom_value?

     private
     def parent_id_custom_value?
          if self.category == "expansion"
               Game.find(self.parent_id)
          end
     end
end

app/models/genre.rb
class Genre < ApplicationRecord
     has_and_belongs_to_many :games
end

app/models/involved_company.rb
class InvolvedCompany < ApplicationRecord
  belongs_to :company
  belongs_to :game

  validates :developer, :publisher, inclusion: {in: [true, false]}
end

app/models/platform.rb
class Platform < ApplicationRecord
     has_and_belongs_to_many :games
     enum category: { console: 0, arcade: 1, platform: 2, operating_system: 3, portable_console: 4, computer: 5 }

     validates :name, :category, presence: true
     validates :name, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :reviewable, polymorphic: true
  after_create :count_up
  after_destroy :count_down
  
  validates :body, presence: true
  validates :title, presence: true, length: { maximum: 40 }

  private
  def count_up
       if self.user.review_count.nil? self.user.update(review_count:0)
       end
       count = self.user.review_count
       self.user.update(review_count: count + 1)
  end
  def count_down
       count = self.user.review_count
       self.user.update(review_count: count + 1)
  end
end

app/models/user.rb
class User < ApplicationRecord
     has_many :reviews
     
     validates :username, :email, presence: true, uniqueness: true
     validates :birth_date, presence: true

     validates :bd_checker, numericality: { less_than: Date.today. year - 16, message: "You should be 16 years old to create an account"}

     private
     def bd_checker
          self.birth_date.year
     end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end
  def show
    @item = Company.find(params[:id])
  end
  def new
    @company = Company.new
  end
  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to company_path(@company)
    else
      render :new
    end
  end
  def edit
    @company = Company.find(params[:id])
  end
  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to(@company)
    else
      render :edit
    end
  end
  def destroy
    company = Company.find(params[:id])
    company.destroy
    redirect_to companies_path
  end
  
  private
  
  def company_params
    params.require(:company).permit(:name, :description, :start_date, :country)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end
  def show
    @item = Game.find(params[:id])
  end
  def new
    @game = Game.new
  end
  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end
  def edit
    @game = Game.find(params[:id])
  end
  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      redirect_to(@game)
    else
      render :edit
    end
  end
  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to games_path
  end
  
  private
  
  def game_params
    params.require(:game).permit(:name, :summary, :release_date, :category, :rating, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/companies/_edit_form.html.erb
<%= form_for(@company) do |f| %>
  <ul>
  <% @company.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date %>
  </p>
  <p>
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit a company</h1>

<%= render partial: 'edit_form' %>

<%= link_to "Back to companies", companies_path %>

app/views/companies/index.html.erb
<h1>All the companies</h1>
<%= link_to "New Compnay", new_company_path %>
<table>
     <tr>
          <th>Name</th>
          <th>Country</th>
          <th></th>
     </tr>
     <% @companies.each do | item | %>
     <tr>
          <td><%=item.name%></td>
          <td><%=item.country%></td>
          <td><%= link_to "Show", company_path(item.id), {:id => item.id}%></td>
          <td><%= link_to "Edit", edit_company_path(item.id), {:id => item.id}%></td>
     </tr>
     <% end %>
</table>

app/views/companies/new.html.erb
<h1>Create a New Game</h1>
<%= form_for(@company) do |f| %>
  <ul>
  <% @company.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date %>
  </p>
  <p>
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back to Games", companies_path %>

app/views/companies/show.html.erb
<h1><%=@item.name%></h1>
<p><%=@item.description%></p>

<li>
  Start date: <%=@item.start_date%>
</li>
<li>
  Country: <%=@item.country%>
</li>
<li>
  Games released: <%=@item.games.map {|game| game.name}.join(", ") %>
</li>
<%= link_to "Delete this Game", company_path(@item), method: :delete, data: { confirm: "Really delete the game?" } %>
<%= link_to "Back to companies", companies_path %>

app/views/games/_edit_form.html.erb
<%= form_for(@game) do |f| %>
  <ul>
  <% @game.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </p>
  <p>
    <%= f.label :release_date %><br />
    <%= f.text_field :release_date %>
  </p>
  <p>
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </p>
  <p>
    <%= f.label :parent_id %><br />
    <%= f.text_field :parent_id %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/games/edit.html.erb
<h1>Edit a Game</h1>

<%= render partial: 'edit_form' %>

<%= link_to "Back to Games", games_path %>

app/views/games/index.html.erb
<h1>All the games</h1>
<%= link_to "New Game", new_game_path %>
<table>
     <tr>
          <th>Name</th>
          <th>Rating</th>
          <th></th>
     </tr>
     <% @games.each do | item | %>
     <tr>
          <td><%=item.name%></td>
          <td><%=item.rating%></td>
          <td><%= link_to "Show", game_path(item.id), {:id => item.id}%></td>
          <td><%= link_to "Edit", edit_game_path(item.id), {:id => item.id}%></td>
     </tr>
     <% end %>
</table>

app/views/games/new.html.erb
<h1>Create a New Game</h1>
<%= form_for(@game) do |f| %>
  <ul>
  <% @game.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </p>
  <p>
    <%= f.label :release_date %><br />
    <%= f.text_field :release_date %>
  </p>
  <p>
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </p>
  <p>
    <%= f.label :parent_id %><br />
    <%= f.text_field :parent_id %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back to Games", games_path %>

app/views/games/show.html.erb
<h1><%=@item.name%></h1>
<p><%=@item.summary%></p>

<li>
  Rating: <%=@item.rating%>
</li>
<li>
  Release date: <%=@item.release_date%>
</li>
<li>
  Platform(s): <%=@item.platforms.map {|platform| platform.name}.join(", ")%>
</li>
<li>
  Genre(s): <%=@item.genres.map {|genre| genre.name}.join(", ")%>
</li>
<%=link_to "Go back to Games", games_path%>
<%=link_to "Delete this Game", game_path(@item), method: :delete, data: { confirm: "Really delete the game?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CriticxAlpha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>